# Generated by Django 4.0.5 on 2022-06-30 05:37

from django.db import migrations
from django.conf import settings


def create_superuser(apps, editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.create_superuser('admin', 'admin@gmail.com', '123456')

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_last_na_2e448d_idx'),
    ]

    #password = 123456
    #username = a1
    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop)
    ]
