# Generated by Django 4.0.5 on 2022-07-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='plated_at',
            new_name='placed_at',
        ),
    ]
