# Generated by Django 4.0.5 on 2022-07-31 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_caritem_cartem_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator]),
        ),
        migrations.AlterUniqueTogether(
            name='cartem',
            unique_together={('cart', 'product')},
        ),
    ]
